"""create_tooltip_suggestions_table

Revision ID: 63000da90103
Revises: 29c8e6a25b9d
Create Date: 2026-03-06 12:47:34.638727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63000da90103'
down_revision: Union[str, Sequence[str], None] = '29c8e6a25b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tooltip_suggestions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('paper_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('entity_label', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('tooltip_content', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suggestion_paper', 'tooltip_suggestions', ['paper_id'], unique=False)
    op.create_index('idx_suggestion_paper_entity', 'tooltip_suggestions', ['paper_id', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_suggestion_paper_entity', table_name='tooltip_suggestions')
    op.drop_index('idx_suggestion_paper', table_name='tooltip_suggestions')
    op.drop_table('tooltip_suggestions')
    # ### end Alembic commands ###
